services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/ajeetraina/labspace-sbx

  # workspace:
  #   # Uncomment to expose sbx ports if needed
  #   ports: !override
  #     - "8080:8080"
